// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotifyNet.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NotifyNet.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbConetxt))]
    [Migration("20250409134634_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AXO.Core.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BuildingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModeration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateOfClose")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateOfExecution")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateWorkStatus")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionDispathcer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionOfWork")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("DivisionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EmployeeApplicantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EmployeeDispatcherId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EmployeeExecuterId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EmployeeNotificationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("OrderNumber")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PriorityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProcessId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RecordId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SupportId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
